"""Private R7 service-contract spec rows (core half)."""

from __future__ import annotations

from typing import Final

_ContractSpec = tuple[str, str, tuple[str, ...], tuple[str, ...], str]

CORE_CONTRACT_SPECS: Final[tuple[_ContractSpec, ...]] = (
    (
        "identity",
        "root",
        (
            "identity.authenticate",
            "identity.delegate",
        ),
        (
            "identity-unresolved",
            "credential-rejected",
        ),
        "same-major-provider-swap",
    ),
    (
        "reality.observe",
        "world",
        (
            "reality.observe.read",
            "reality.observe.stream",
        ),
        (
            "observation-rejected",
            "scope-denied",
        ),
        "additive-minor",
    ),
    (
        "reality.proposal",
        "world",
        (
            "reality.propose.command",
            "reality.propose.delta",
        ),
        (
            "proposal-rejected",
            "stale-revision",
        ),
        "additive-minor",
    ),
    (
        "reality.policy",
        "tenant",
        (
            "reality.policy.evaluate",
            "reality.policy.publish",
        ),
        (
            "policy-conflict",
            "policy-unsatisfied",
        ),
        "same-major-provider-swap",
    ),
    (
        "authority",
        "root",
        (
            "authority.commit",
            "authority.audit",
        ),
        (
            "not-commit-authority",
            "stale-revision",
        ),
        "same-major-provider-swap",
    ),
    (
        "history",
        "worldline",
        (
            "history.append",
            "history.read",
        ),
        (
            "append-conflict",
            "history-gap",
        ),
        "same-major-provider-swap",
    ),
    (
        "branch",
        "worldline",
        (
            "branch.fork",
            "branch.merge",
        ),
        (
            "branch-diverged",
            "stale-branch-revision",
        ),
        "additive-minor",
    ),
    (
        "lineage",
        "worldline",
        (
            "lineage.trace",
            "lineage.verify",
        ),
        (
            "lineage-broken",
            "unknown-ancestor",
        ),
        "same-major-provider-swap",
    ),
    (
        "replay",
        "worldline",
        (
            "replay.from-event",
            "replay.verify",
        ),
        (
            "replay-divergence",
            "history-unavailable",
        ),
        "same-major-provider-swap",
    ),
    (
        "evidence",
        "world",
        (
            "evidence.record",
            "evidence.verify",
        ),
        (
            "evidence-missing",
            "digest-mismatch",
        ),
        "additive-minor",
    ),
    (
        "rights",
        "tenant",
        (
            "rights.grant",
            "rights.revoke",
        ),
        (
            "right-denied",
            "right-unknown",
        ),
        "additive-minor",
    ),
    (
        "execution",
        "world",
        (
            "execution.schedule",
            "execution.cancel",
        ),
        (
            "execution-rejected",
            "runtime-unavailable",
        ),
        "same-major-provider-swap",
    ),
    (
        "actor",
        "world",
        (
            "actor.observe",
            "actor.control",
        ),
        (
            "actor-unresolved",
            "control-denied",
        ),
        "additive-minor",
    ),
    (
        "model",
        "tenant",
        (
            "model.invoke",
            "model.qualify",
        ),
        (
            "model-unavailable",
            "qualification-failed",
        ),
        "same-major-provider-swap",
    ),
)
