"""Private R7 service-contract spec rows (extended half)."""

from __future__ import annotations

from typing import Final

_ContractSpec = tuple[str, str, tuple[str, ...], tuple[str, ...], str]

EXTENDED_CONTRACT_SPECS: Final[tuple[_ContractSpec, ...]] = (
    (
        "capability",
        "root",
        (
            "capability.register",
            "capability.resolve",
        ),
        (
            "capability-unknown",
            "capability-conflict",
        ),
        "additive-minor",
    ),
    (
        "world.metadata",
        "world",
        (
            "world.metadata.read",
            "world.metadata.propose",
        ),
        (
            "metadata-unavailable",
            "metadata-change-rejected",
        ),
        "additive-minor",
    ),
    (
        "snapshot",
        "worldline",
        (
            "snapshot.create",
            "snapshot.read",
        ),
        (
            "snapshot-unavailable",
            "snapshot-incompatible",
        ),
        "same-major-provider-swap",
    ),
    (
        "clock",
        "world",
        (
            "clock.read",
            "clock.advance",
        ),
        (
            "clock-unavailable",
            "clock-transition-rejected",
        ),
        "additive-minor",
    ),
    (
        "space",
        "world",
        (
            "space.query",
            "space.resolve",
        ),
        (
            "space-unavailable",
            "space-resolution-failed",
        ),
        "additive-minor",
    ),
    (
        "memory",
        "worldline",
        (
            "memory.record",
            "memory.recall",
        ),
        (
            "memory-unavailable",
            "memory-scope-denied",
        ),
        "additive-minor",
    ),
    (
        "simulation",
        "world",
        (
            "simulation.run",
            "simulation.checkpoint",
        ),
        (
            "simulation-rejected",
            "simulation-unavailable",
        ),
        "same-major-provider-swap",
    ),
    (
        "forge.world",
        "root",
        (
            "forge.world.compile",
            "forge.world.validate",
        ),
        (
            "world-compile-failed",
            "world-package-invalid",
        ),
        "additive-minor",
    ),
    (
        "forge.capability",
        "root",
        (
            "forge.capability.compile",
            "forge.capability.verify",
        ),
        (
            "capability-compile-failed",
            "capability-verification-failed",
        ),
        "additive-minor",
    ),
    (
        "projection",
        "world",
        (
            "projection.describe",
            "projection.render",
        ),
        (
            "projection-unavailable",
            "projection-unsupported",
        ),
        "additive-minor",
    ),
    (
        "experience",
        "world",
        (
            "experience.enter",
            "experience.continue",
        ),
        (
            "experience-unavailable",
            "experience-entry-denied",
        ),
        "additive-minor",
    ),
    (
        "distribution",
        "world",
        (
            "distribution.build",
            "distribution.publish",
        ),
        (
            "distribution-unsupported",
            "distribution-policy-denied",
        ),
        "additive-minor",
    ),
    (
        "reality.profile",
        "world",
        (
            "reality.profile.read",
            "reality.profile.lock",
        ),
        (
            "profile-unknown",
            "profile-mismatch",
        ),
        "additive-minor",
    ),
)
