// GENERATED by scripts/export_r7_service_contracts.py. DO NOT EDIT.
export const GENERATED_SERVICE_CONTRACTS = [
  { namespace: "wanxiang.identity", apiVersion: "1", scope: "root" },
  { namespace: "wanxiang.reality.observe", apiVersion: "1", scope: "world" },
  { namespace: "wanxiang.reality.proposal", apiVersion: "1", scope: "world" },
  { namespace: "wanxiang.reality.policy", apiVersion: "1", scope: "tenant" },
  { namespace: "wanxiang.authority", apiVersion: "1", scope: "root" },
  { namespace: "wanxiang.history", apiVersion: "1", scope: "worldline" },
  { namespace: "wanxiang.branch", apiVersion: "1", scope: "worldline" },
  { namespace: "wanxiang.lineage", apiVersion: "1", scope: "worldline" },
  { namespace: "wanxiang.replay", apiVersion: "1", scope: "worldline" },
  { namespace: "wanxiang.evidence", apiVersion: "1", scope: "world" },
  { namespace: "wanxiang.rights", apiVersion: "1", scope: "tenant" },
  { namespace: "wanxiang.execution", apiVersion: "1", scope: "world" },
  { namespace: "wanxiang.actor", apiVersion: "1", scope: "world" },
  { namespace: "wanxiang.model", apiVersion: "1", scope: "tenant" },
  { namespace: "wanxiang.capability", apiVersion: "1", scope: "root" },
  { namespace: "wanxiang.reality.profile", apiVersion: "1", scope: "world" },
] as const;
