"""Source registry & source gate substrate (G04B)."""

from wanxiang_substrate.sources.adapter import (
    AdapterRegistry,
    IngestResult,
    ReferenceTextAdapter,
    SourceAdapter,
    SourceInspection,
    require_text,
)
from wanxiang_substrate.sources.asset import AssetAdapter, GenericAsset, kind_for, register_asset
from wanxiang_substrate.sources.blob import BlobRef, SourceBlobStore, is_blob_uri
from wanxiang_substrate.sources.book import BookAdapter, Chapter
from wanxiang_substrate.sources.canon import (
    CanonClaim,
    CanonCompiler,
    CompiledCanon,
    ScenarioPoint,
    scenario_at,
)
from wanxiang_substrate.sources.character import (
    CharacterCanon,
    CharacterDistiller,
    CharacterFact,
    FactKind,
    FactScope,
    KnowledgeBoundary,
    RelationClaim,
)
from wanxiang_substrate.sources.entity_distill import (
    DistilledEntities,
    EntityCandidate,
    EntityConnection,
    EntityDistiller,
    EntityMention,
    EntityReviewDecision,
    EntityReviewGate,
)
from wanxiang_substrate.sources.errors import (
    CapabilityUnavailable,
    DuplicateSource,
    IngestError,
    InvalidTransition,
    MalformedSourceContent,
    MaliciousSource,
    OcrRequired,
    RightsDenied,
    SemanticProviderRequired,
    SemanticProviderSchemaError,
    SourceError,
    SourceNotApproved,
    SourceNotFound,
    UnsupportedSource,
    ZeroCoverage,
)
from wanxiang_substrate.sources.evidence import AUTHORIZED_REVIEWERS, evidence_ok
from wanxiang_substrate.sources.fixture import (
    approved_source,
    conflicting_claims,
    conflicting_sources,
    malicious_source,
    rejected_source,
)
from wanxiang_substrate.sources.gate import GateDecision, SourceGate
from wanxiang_substrate.sources.identity import (
    AliasClaim,
    IdentityCandidate,
    IdentityDistiller,
    IdentityReviewDecision,
    IdentityReviewGate,
    identity_to_claim,
)
from wanxiang_substrate.sources.locator import (
    SourceLocator,
    locator_stable_hash,
    segment_source,
    source_slice,
)
from wanxiang_substrate.sources.model import (
    VALID_SOURCE_ACCESS,
    ClaimCandidate,
    EvidenceLink,
    RightsEnvelope,
    SourceAccess,
    SourceRecord,
    payload_hash,
)
from wanxiang_substrate.sources.policy import SourcePolicy
from wanxiang_substrate.sources.registry import AuditEntry, SourceRegistry
from wanxiang_substrate.sources.security import (
    CorruptSource,
    EncryptedSource,
    IngestSecurityError,
    IngestSecurityGate,
    PathTraversal,
    SecurityCheck,
    SourceSizeExceeded,
    UndecodableSource,
    ZipBomb,
    check_archive,
)
from wanxiang_substrate.sources.structured import StructuredAdapter

__all__ = [
    "AdapterRegistry",
    "BlobRef",
    "BookAdapter",
    "CorruptSource",
    "EncryptedSource",
    "IngestSecurityError",
    "IngestSecurityGate",
    "PathTraversal",
    "SecurityCheck",
    "SourceSizeExceeded",
    "UndecodableSource",
    "ZipBomb",
    "check_archive",
    "AssetAdapter",
    "Chapter",
    "GenericAsset",
    "kind_for",
    "register_asset",
    "StructuredAdapter",
    "IngestError",
    "IngestResult",
    "MalformedSourceContent",
    "OcrRequired",
    "ReferenceTextAdapter",
    "SourceAdapter",
    "SourceInspection",
    "UnsupportedSource",
    "require_text",
    "BlobRef",
    "AuditEntry",
    "CharacterCanon",
    "CharacterDistiller",
    "CharacterFact",
    "FactKind",
    "FactScope",
    "KnowledgeBoundary",
    "RelationClaim",
    "CanonClaim",
    "CanonCompiler",
    "CompiledCanon",
    "ScenarioPoint",
    "scenario_at",
    "AUTHORIZED_REVIEWERS",
    "DistilledEntities",
    "EntityCandidate",
    "EntityConnection",
    "EntityDistiller",
    "EntityMention",
    "EntityReviewDecision",
    "EntityReviewGate",
    "evidence_ok",
    "ClaimCandidate",
    "DuplicateSource",
    "CapabilityUnavailable",
    "SemanticProviderRequired",
    "SemanticProviderSchemaError",
    "ZeroCoverage",
    "EvidenceLink",
    "GateDecision",
    "AliasClaim",
    "IdentityCandidate",
    "IdentityDistiller",
    "IdentityReviewDecision",
    "IdentityReviewGate",
    "identity_to_claim",
    "InvalidTransition",
    "MaliciousSource",
    "RightsDenied",
    "RightsEnvelope",
    "SourceError",
    "SourceGate",
    "SourceNotApproved",
    "SourceNotFound",
    "SourceAccess",
    "SourcePolicy",
    "SourceRecord",
    "SourceBlobStore",
    "SourceRegistry",
    "VALID_SOURCE_ACCESS",
    "approved_source",
    "conflicting_claims",
    "conflicting_sources",
    "malicious_source",
    "payload_hash",
    "rejected_source",
    "SourceLocator",
    "is_blob_uri",
    "locator_stable_hash",
    "segment_source",
    "source_slice",
]
