"""Generate the Cordis host's service-contract identity projection.

Python owns the complete R7 ServiceContract definitions. The TypeScript host
needs only namespace/API-version/scope for composition, so this generator keeps
that projection mechanically synchronized instead of maintaining a second table.
"""

from __future__ import annotations

from pathlib import Path

from wanxiang_reality.contracts import SERVICE_CONTRACTS

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "packages" / "cordis_host" / "src" / "contracts.generated.ts"


def render() -> str:
    lines = [
        "// GENERATED by scripts/export_r7_service_contracts.py. DO NOT EDIT.",
        "export const GENERATED_SERVICE_CONTRACTS = [",
    ]
    for contract in SERVICE_CONTRACTS:
        lines.append(
            "  { "
            f'namespace: "{contract.namespace}", '
            f'apiVersion: "{contract.api_version}", '
            f'scope: "{contract.scope}"'
            " },"
        )
    lines.extend(("] as const;", ""))
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"exported {len(SERVICE_CONTRACTS)} R7 service contracts to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
